### PR TITLE
slight update to build

### PR DESCRIPTION
**Pull request by cympfh**
v1.0.3 cannot build with my rust `1.54.0` with 2 errors.
This PR resolves them.

```bash
$ rustc -V
rustc 1.54.0 (a178d0322 2021-07-26)

$ cargo install git-hist --version 1.0.3

[..]

error[E0599]: no variant or associated item named `AllowEmptyValues` found for enum `ArgSettings` in the current scope
  --> /home/kazuhiro_hattori/.cargo/registry/src/github.com-1ecc6299db9ec823/git-hist-1.0.3/src/args.rs:76:43
   |
76 |                     .setting(ArgSettings::AllowEmptyValues)
   |                                           ^^^^^^^^^^^^^^^^
   |                                           |
   |                                           variant or associated item not found in `ArgSettings`
   |                                           help: there is a variant with a similar name: `AllowHyphenValues`

[..]

error[E0277]: `(dyn std::error::Error + 'static)` cannot be shared between threads safely
   --> /home/kazuhiro_hattori/.cargo/registry/src/github.com-1ecc6299db9ec823/git-hist-1.0.3/src/args.rs:110:63
    |
110 |         let tab_size = matches.value_of_t::<usize>("tab-size")?;
    |                                                               ^ `(dyn std::error::Error + 'static)` cannot be shared between threads safely
    |
    = help: the trait `Sync` is not implemented for `(dyn std::error::Error + 'static)`
    = note: required because of the requirements on the impl of `Sync` for `std::ptr::Unique<(dyn std::error::Error + 'static)>`
    = note: required because it appears within the type `Box<(dyn std::error::Error + 'static)>`
    = note: required because it appears within the type `Option<Box<(dyn std::error::Error + 'static)>>`
    = note: required because it appears within the type `clap::Error`
    = note: required because of the requirements on the impl of `From<clap::Error>` for `anyhow::Error`
    = note: required because of the requirements on the impl of `FromResidual<Result<Infallible, clap::Error>>` for `Result<args::Args, anyhow::Error>`
    = note: required by `from_residual`

```

### CODE REVIEW

File: src/args.rs [hunk 1]
```diff
@@ -107,7 +106,9 @@ impl Args {
         };
         let date_format = String::from(matches.value_of("date-format").unwrap());
 
-        let tab_size = matches.value_of_t::<usize>("tab-size")?;
+        let tab_size = matches
+            .value_of_t::<usize>("tab-size")
+            .unwrap_or_else(|e| e.exit());
```
Comment (arkark) [inline src/args.rs:111]: This change is good, but this function no longer returns `anyhow::Error`.
So, I prefer `pub fn load() -> Args` to `pub fn load() -> Result<Args>`. Please also change it.

**Review by arkark — CHANGES_REQUESTED** [review]
Thanks for your contribution.
It looks mostly good, but please fix one I pointed out.

File: src/args.rs (hunk 1 above)
Comment (cympfh) [reply src/args.rs:110]: Ok, I have changed. Check again please.

**Review by arkark — APPROVED** [review]
